name: Test cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Save test
        run: env > ~/test

      - name: Save test
        run: echo build-${{ hashFiles('/home/runner/test') }}

      - name: Print test
        run: cat ~/test

      - name: Cache file
        id: cache
        uses: actions/cache@v2

        with:
          path: ~/test
          key: ${{ runner.os }}3-build-${{ hashFiles('**/test') }}
          restore-keys: |
            ${{ runner.os }}3-build-
            ${{ runner.os }}3-

      - name: Print test
        if: steps.cache.outputs.cache-hit
        run: cat ~/test
