name: Test cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache file
        id: cache
        uses: actions/cache@v2

        with:
          path: ~/test
          key: ${{ runner.os }}2-build2-${{ hashFiles('~/test') }}
          restore-keys: |
            ${{ runner.os }}2-build2-
            ${{ runner.os }}2-

      - name: Print test
        if: steps.cache.outputs.cache-hit
        run: cat ~/test

      - name: Save test
        run: env > ~/test
